name: Deploy to EC2

on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Navigate to the app directory
        run: cd /home/ubuntu/todo-list-backend
      - name: Pull Docker
        run: docker pull danninon/todo-list-backend:main
      - name: Debug - List Current Directory
        run: ls -l
      - name: Debug - Print Current Directory
        run: pwd
      - name: Debug - List Specific Path
        run: ls -l /home/ubuntu/todo-list-backend
      - name: Remove Containers
        working-directory: /home/ubuntu/todo-list-backend
        run: docker compose down
      - name: Run Docker Containers Detached
        working-directory: /home/ubuntu/todo-list-backend
        run: docker compose up -d
