name: Deploy to EC2

on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Navigate to the app directory
        run: cd /home/ubuntu/todo-list-backend
      - name: Pull Docker
        run: docker pull danninon/todo-list-backend:main
      - name: Remove Containers
        working-directory: /home/ubuntu/todo-list-backend
        run: docker compose down
      - name: Run Docker Containers Detached
        working-directory: /home/ubuntu/todo-list-backend
        run: docker compose up -d
